### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by czha5168** [Jia-Research-Lab/PointGroup#10]
Hi Jia,
Thanks for your interesting project. I wonder whether you could help me go through the compiling & installation step.
I was stuck at the following scripts, where any detailed comments/instructions to help me understand with would be very appreciated. This part lead to a failing "python setup.py bdist_wheel" I suppose
"Add the $INCLUDE_PATH$ that contains boost in lib/spconv/CMakeLists.txt. (Not necessary if it could be found.)
include_directories($INCLUDE_PATH$)"

Thanks for your time!

**Comment by BanaBear** [comment]
have you solve this problem? i would like to know how to solve this problem, thank you.

**Comment by BanaBear** [comment]
@czha5168

**Comment by BanaBear** [comment]
i have solved this problem, first, ensure that your spconv==1.0, you can download from https://github.com/traveller59/spconv/tree/8da6f967fb9a054d8870c3515b1b44eca2103634, second, use sudo apt-get install libboostall-dev.
