### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by pengliu380** [Jia-Research-Lab/PointGroup#11]
Hi  Jiang,
     It seems that it will take a long time to train the whole model on a single gpu. So I want to know how long it will take you to finish the training. And have you used any methods to speed up the training, like multi-gpu-training?
Thanks!

**Comment by llijiang** [comment]
Hi,
It takes 2 to 3 days to train on a single GPU. 
Multi-GPU training could speed up the training. 
I will release a multi-GPU version later.

**Comment by pengliu380** [comment]
Thanks!

**Comment by MrCrazyCrab** [comment]
@pengliu380  hou much gpu do you use to train the model?

**Comment by qzhou711** [comment]
Hi @llijiang , 
When will you release the multi-GPU version?

**Comment by pengliu380** [comment]
> @pengliu380 hou much gpu do you use to train the model?

One is enough
