### ISSUE TITLE
Error while compiling pointgroup_ops library

### ISSUE THREAD

**Issue by a06271010** [Jia-Research-Lab/PointGroup#16]
I have met some error when I compiled pointgroup_ops library. The error is:

running build_ext
building 'PG_OP' extension
gcc -pthread -B /home/xiaojiwei/anaconda2/envs/pointgroup1/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/xiaojiwei/anaconda2/envs/pointgroup1/lib/python3.7/site-packages/torch/include -I/home/xiaojiwei/anaconda2/envs/pointgroup1/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/xiaojiwei/anaconda2/envs/pointgroup1/lib/python3.7/site-packages/torch/include/TH -I/home/xiaojiwei/anaconda2/envs/pointgroup1/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/xiaojiwei/3Dseg/PointGroup/lib/pointgroup_ops/google -I/home/xiaojiwei/anaconda2/envs/pointgroup1/include/python3.7m -c src/pointgroup_ops_api.cpp -o build/temp.linux-x86_64-3.7/src/pointgroup_ops_api.o -g -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=PG_OP -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from src/pointgroup_ops.h:3:0,
                 from src/pointgroup_ops_api.cpp:4:
src/datatype/datatype.h:7:33: fatal error: google/dense_hash_map: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1

I have tried to use add the --include-dirs following your instruction, but it seem didn't work.

**Comment by lqzhao** [comment]
Hi, how did you solve the problem?

**Comment by lqzhao** [comment]
> Hi, how did you solve the problem?

Solved by `**apt-get install libsparsehash-dev**`

**Comment by lluma** [comment]
I solved by adding my conda include directory to your environment variable INCLUDE_PATH.
```bash
export INCLUDE_PATH=~/.conda/envs/pointgroup/include:$INCLUDE_PATH
```
after I ran the following commands
```bash
python setup.py build_ext --include-dirs=$INCLUDE_PATH$
python setup.py develop
```
