### ISSUE TITLE
Support spconv=1.1 ?

### ISSUE THREAD

**Issue by sidml** [Jia-Research-Lab/PointGroup#2]
Hi.
I was wondering if you are planning to add support for spconv 1.1. Spconv seems to compile smoothly for Python3.7, Cuda 10.2 and Pytorch 1.5. 
Spconv 1.0 doesn't seem to work with Pytorch 1.1.
Perhaps the [changes](https://github.com/llijiang/spconv/commit/740a5b717fc576b222abc169ae6047ff1e95363f) in the spconv/functional.py code are sufficient to ensure compatibility with PointGroup code.
Thanks.

**Comment by llijiang** [comment]
Hi,
You could use spconv1.1 with the changes in the spconv/functional.py. 
I have roughly tested the newest spconv 1.2.1 with:
* Python 3.7
* CUDA 10.1
* Pytorch 1.3
* torchvision 0.4.1
* cuDNN 7.6.5

It seems that the changes in the spconv/functional.py is enough.
