### ISSUE TITLE
undefined symbol: _ZN6caffe26detail36_typeMetaDataInstance_preallocated_7E

### ISSUE THREAD

**Issue by 3bobo** [Jia-Research-Lab/PointGroup#21]
After successfully compiling pointgroup_ops, I try to import it. However, there is an error: 
`pointgroup_ops/point_group.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail36_typeMetaDataInstance_preallocated_7E`

I use torch 1.1.0, torchvision 0.3.0,  spconv 1.0, python 3.7.7

**Comment by fuy34** [comment]
Hey, I met a similar  issue. Did you figure it out?

The one I got
```
ImportError: /path/to/the/master_dir/PointGroup/lib/pointgroup_ops/PG_OP.cpython-37m-x86_64-linux-gnu.so:
undefined symbol: _ZN6caffe26detail36_typeMetaDataInstance_preallocated_7E
```
