### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by cuge1995** [Jia-Research-Lab/PointGroup#5]
when run ''python setup.py bdist_wheel'', and I've set set(CMAKE_CUDA_COMPILER "/usr/local/cuda/bin/nvcc")

-- The CUDA compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CUDA_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CUDACXX" or the CMake cache entry CMAKE_CUDA_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!

**Comment by llijiang** [comment]
Hi, you may refer to the similar [issue](https://github.com/jetsonhacks/buildLibrealsense2TX/issues/13) for some help.

**Comment by cuge1995** [comment]
-- The CUDA compiler identification is NVIDIA 10.1.243
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CUDA: /usr/local/cuda (found version "10.1")
-- Caffe2: CUDA detected: 10.1
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 10.1
CMake Warning (dev) at /home/cuge/anaconda3/envs/pointgroup/lib/python3.7/site-packages/cmake/data/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (CUDNN) does
  not match the name of the calling package (Caffe2).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /home/cuge/anaconda3/envs/pointgroup/lib/python3.7/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:107 (find_package_handle_standard_args)
  /home/cuge/anaconda3/envs/pointgroup/lib/python3.7/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  /home/cuge/anaconda3/envs/pointgroup/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:40 (find_package)
  CMakeLists.txt:25 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find CUDNN (missing: CUDNN_INCLUDE_DIR CUDNN_LIBRARY)
CMake Warning at /home/cuge/anaconda3/envs/pointgroup/lib/python3.7/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:110 (message):
  Caffe2: Cannot find cuDNN library.  Turning the option off
Call Stack (most recent call first):
  /home/cuge/anaconda3/envs/pointgroup/lib/python3.7/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  /home/cuge/anaconda3/envs/pointgroup/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:40 (find_package)
  CMakeLists.txt:25 (find_package)


-- Autodetected CUDA architecture(s):  6.1 6.1
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
CMake Error at /home/cuge/anaconda3/envs/pointgroup/lib/python3.7/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:96 (message):
  Your installed Caffe2 version uses cuDNN but I cannot find the cuDNN
  libraries.  Please set the proper cuDNN prefixes and / or install cuDNN.
Call Stack (most recent call first):
  /home/cuge/anaconda3/envs/pointgroup/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:40 (find_package)
  CMakeLists.txt:25 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/cuge/Documents/point/PointGroup/lib/spconv/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeOutput.log".
See also "/home/cuge/Documents/point/PointGroup/lib/spconv/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 86, in <module>
    zip_safe=False,
  File "/home/cuge/anaconda3/envs/pointgroup/lib/python3.7/site-packages/setuptools/__init__.py", line 161, in setup
    return distutils.core.setup(**attrs)
  File "/home/cuge/anaconda3/envs/pointgroup/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/cuge/anaconda3/envs/pointgroup/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/cuge/anaconda3/envs/pointgroup/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/cuge/anaconda3/envs/pointgroup/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 223, in run
    self.run_command('build')
  File "/home/cuge/anaconda3/envs/pointgroup/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/cuge/anaconda3/envs/pointgroup/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/cuge/anaconda3/envs/pointgroup/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/cuge/anaconda3/envs/pointgroup/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/cuge/anaconda3/envs/pointgroup/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 39, in run
    self.build_extension(ext)
  File "setup.py", line 69, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/home/cuge/anaconda3/envs/pointgroup/lib/python3.7/subprocess.py", line 328, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/cuge/Documents/point/PointGroup/lib/spconv', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/cuge/Documents/point/PointGroup/lib/spconv/build/lib.linux-x86_64-3.7/spconv', '-DCMAKE_PREFIX_PATH=/home/cuge/anaconda3/envs/pointgroup/lib/python3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr"', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.

**Comment by cuge1995** [comment]
still cannot work

**Comment by liudaizong** [comment]
> -- The CUDA compiler identification is NVIDIA 10.1.243
> -- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
> -- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - works
> -- Detecting CUDA compiler ABI info
> -- Detecting CUDA compiler ABI info - done
> -- Detecting CUDA compile features
> -- Detecting CUDA compile features - done
> -- Looking for C++ include pthread.h
> -- Looking for C++ include pthread.h - found
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE
> -- Found CUDA: /usr/local/cuda (found version "10.1")
> -- Caffe2: CUDA detected: 10.1
> -- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
> -- Caffe2: CUDA toolkit directory: /usr/local/cuda
> -- Caffe2: Header version is: 10.1
> CMake Warning (dev) at /home/cuge/anaconda3/envs/pointgroup/lib/python3.7/site-packages/cmake/data/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
> The package name passed to `find_package_handle_standard_args` (CUDNN) does
> not match the name of the calling package (Caffe2). This can lead to
> problems in calling code that expects `find_package` result variables
> (e.g., `_FOUND`) to follow a certain pattern.
> Call Stack (most recent call first):
> /home/cuge/anaconda3/envs/pointgroup/lib/python3.7/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:107 (find_package_handle_standard_args)
> /home/cuge/anaconda3/envs/pointgroup/lib/python3.7/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
> /home/cuge/anaconda3/envs/pointgroup/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:40 (find_package)
> CMakeLists.txt:25 (find_package)
> This warning is for project developers. Use -Wno-dev to suppress it.
> 
> -- Could NOT find CUDNN (missing: CUDNN_INCLUDE_DIR CUDNN_LIBRARY)
> CMake Warning at /home/cuge/anaconda3/envs/pointgroup/lib/python3.7/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:110 (message):
> Caffe2: Cannot find cuDNN library. Turning the option off
> Call Stack (most recent call first):
> /home/cuge/anaconda3/envs/pointgroup/lib/python3.7/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
> /home/cuge/anaconda3/envs/pointgroup/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:40 (find_package)
> CMakeLists.txt:25 (find_package)
> 
> -- Autodetected CUDA architecture(s): 6.1 6.1
> -- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
> CMake Error at /home/cuge/anaconda3/envs/pointgroup/lib/python3.7/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:96 (message):
> Your installed Caffe2 version uses cuDNN but I cannot find the cuDNN
> libraries. Please set the proper cuDNN prefixes and / or install cuDNN.
> Call Stack (most recent call first):
> /home/cuge/anaconda3/envs/pointgroup/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:40 (find_package)
> CMakeLists.txt:25 (find_package)
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/cuge/Documents/point/PointGroup/lib/spconv/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeOutput.log".
> See also "/home/cuge/Documents/point/PointGroup/lib/spconv/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeError.log".
> Traceback (most recent call last):
> File "setup.py", line 86, in 
> zip_safe=False,
> File "/home/cuge/anaconda3/envs/pointgroup/lib/python3.7/site-packages/setuptools/**init**.py", line 161, in setup
> return distutils.core.setup(**attrs)
> File "/home/cuge/anaconda3/envs/pointgroup/lib/python3.7/distutils/core.py", line 148, in setup
> dist.run_commands()
> File "/home/cuge/anaconda3/envs/pointgroup/lib/python3.7/distutils/dist.py", line 966, in run_commands
> self.run_command(cmd)
> File "/home/cuge/anaconda3/envs/pointgroup/lib/python3.7/distutils/dist.py", line 985, in run_command
> cmd_obj.run()
> File "/home/cuge/anaconda3/envs/pointgroup/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 223, in run
> self.run_command('build')
> File "/home/cuge/anaconda3/envs/pointgroup/lib/python3.7/distutils/cmd.py", line 313, in run_command
> self.distribution.run_command(command)
> File "/home/cuge/anaconda3/envs/pointgroup/lib/python3.7/distutils/dist.py", line 985, in run_command
> cmd_obj.run()
> File "/home/cuge/anaconda3/envs/pointgroup/lib/python3.7/distutils/command/build.py", line 135, in run
> self.run_command(cmd_name)
> File "/home/cuge/anaconda3/envs/pointgroup/lib/python3.7/distutils/cmd.py", line 313, in run_command
> self.distribution.run_command(command)
> File "/home/cuge/anaconda3/envs/pointgroup/lib/python3.7/distutils/dist.py", line 985, in run_command
> cmd_obj.run()
> File "setup.py", line 39, in run
> self.build_extension(ext)
> File "setup.py", line 69, in build_extension
> subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
> File "/home/cuge/anaconda3/envs/pointgroup/lib/python3.7/subprocess.py", line 328, in check_call
> raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['cmake', '/home/cuge/Documents/point/PointGroup/lib/spconv', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/cuge/Documents/point/PointGroup/lib/spconv/build/lib.linux-x86_64-3.7/spconv', '-DCMAKE_PREFIX_PATH=/home/cuge/anaconda3/envs/pointgroup/lib/python3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr"', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.

I also compile it with such issues. How to solve it?

**Comment by VIMLab-hfut** [comment]
> > -- The CUDA compiler identification is NVIDIA 10.1.243
> > -- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
> > -- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - works
> > -- Detecting CUDA compiler ABI info
> > -- Detecting CUDA compiler ABI info - done
> > -- Detecting CUDA compile features
> > -- Detecting CUDA compile features - done
> > -- Looking for C++ include pthread.h
> > -- Looking for C++ include pthread.h - found
> > -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
> > -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
> > -- Looking for pthread_create in pthreads
> > -- Looking for pthread_create in pthreads - not found
> > -- Looking for pthread_create in pthread
> > -- Looking for pthread_create in pthread - found
> > -- Found Threads: TRUE
> > -- Found CUDA: /usr/local/cuda (found version "10.1")
> > -- Caffe2: CUDA detected: 10.1
> > -- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
> > -- Caffe2: CUDA toolkit directory: /usr/local/cuda
> > -- Caffe2: Header version is: 10.1
> > CMake Warning (dev) at /home/cuge/anaconda3/envs/pointgroup/lib/python3.7/site-packages/cmake/data/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
> > The package name passed to `find_package_handle_standard_args` (CUDNN) does
> > not match the name of the calling package (Caffe2). This can lead to
> > problems in calling code that expects `find_package` result variables
> > (e.g., `_FOUND`) to follow a certain pattern.
> > Call Stack (most recent call first):
> > /home/cuge/anaconda3/envs/pointgroup/lib/python3.7/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:107 (find_package_handle_standard_args)
> > /home/cuge/anaconda3/envs/pointgroup/lib/python3.7/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
> > /home/cuge/anaconda3/envs/pointgroup/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:40 (find_package)
> > CMakeLists.txt:25 (find_package)
> > This warning is for project developers. Use -Wno-dev to suppress it.
> > -- Could NOT find CUDNN (missing: CUDNN_INCLUDE_DIR CUDNN_LIBRARY)
> > CMake Warning at /home/cuge/anaconda3/envs/pointgroup/lib/python3.7/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:110 (message):
> > Caffe2: Cannot find cuDNN library. Turning the option off
> > Call Stack (most recent call first):
> > /home/cuge/anaconda3/envs/pointgroup/lib/python3.7/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
> > /home/cuge/anaconda3/envs/pointgroup/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:40 (find_package)
> > CMakeLists.txt:25 (find_package)
> > -- Autodetected CUDA architecture(s): 6.1 6.1
> > -- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
> > CMake Error at /home/cuge/anaconda3/envs/pointgroup/lib/python3.7/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:96 (message):
> > Your installed Caffe2 version uses cuDNN but I cannot find the cuDNN
> > libraries. Please set the proper cuDNN prefixes and / or install cuDNN.
> > Call Stack (most recent call first):
> > /home/cuge/anaconda3/envs/pointgroup/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:40 (find_package)
> > CMakeLists.txt:25 (find_package)
> > -- Configuring incomplete, errors occurred!
> > See also "/home/cuge/Documents/point/PointGroup/lib/spconv/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeOutput.log".
> > See also "/home/cuge/Documents/point/PointGroup/lib/spconv/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeError.log".
> > Traceback (most recent call last):
> > File "setup.py", line 86, in
> > zip_safe=False,
> > File "/home/cuge/anaconda3/envs/pointgroup/lib/python3.7/site-packages/setuptools/**init**.py", line 161, in setup
> > return distutils.core.setup(**attrs)
> > File "/home/cuge/anaconda3/envs/pointgroup/lib/python3.7/distutils/core.py", line 148, in setup
> > dist.run_commands()
> > File "/home/cuge/anaconda3/envs/pointgroup/lib/python3.7/distutils/dist.py", line 966, in run_commands
> > self.run_command(cmd)
> > File "/home/cuge/anaconda3/envs/pointgroup/lib/python3.7/distutils/dist.py", line 985, in run_command
> > cmd_obj.run()
> > File "/home/cuge/anaconda3/envs/pointgroup/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 223, in run
> > self.run_command('build')
> > File "/home/cuge/anaconda3/envs/pointgroup/lib/python3.7/distutils/cmd.py", line 313, in run_command
> > self.distribution.run_command(command)
> > File "/home/cuge/anaconda3/envs/pointgroup/lib/python3.7/distutils/dist.py", line 985, in run_command
> > cmd_obj.run()
> > File "/home/cuge/anaconda3/envs/pointgroup/lib/python3.7/distutils/command/build.py", line 135, in run
> > self.run_command(cmd_name)
> > File "/home/cuge/anaconda3/envs/pointgroup/lib/python3.7/distutils/cmd.py", line 313, in run_command
> > self.distribution.run_command(command)
> > File "/home/cuge/anaconda3/envs/pointgroup/lib/python3.7/distutils/dist.py", line 985, in run_command
> > cmd_obj.run()
> > File "setup.py", line 39, in run
> > self.build_extension(ext)
> > File "setup.py", line 69, in build_extension
> > subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
> > File "/home/cuge/anaconda3/envs/pointgroup/lib/python3.7/subprocess.py", line 328, in check_call
> > raise CalledProcessError(retcode, cmd)
> > subprocess.CalledProcessError: Command '['cmake', '/home/cuge/Documents/point/PointGroup/lib/spconv', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/cuge/Documents/point/PointGroup/lib/spconv/build/lib.linux-x86_64-3.7/spconv', '-DCMAKE_PREFIX_PATH=/home/cuge/anaconda3/envs/pointgroup/lib/python3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr"', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
> 
> I also compile it with such issues. How to solve it?

Hello, have you solved this problem, I also encountered the same problem.Thanks for your time!
