### ISSUE TITLE
Data augmentation in the test time?

### ISSUE THREAD

**Issue by Sekunde** [Jia-Research-Lab/PointGroup#6]
Are the rot and flip also happening in test time?

https://github.com/Jia-Research-Lab/PointGroup/blob/master/data/scannetv2_inst.py#L336-L337

**Comment by llijiang** [comment]
Yes. This part follows the SparseConvNet. 
Its original purpose is to fuse prediction with different augmentation to get a better final prediction. 
We only use one view in our testing process. So maybe we could also remove the rot and flip in test time.
