### ISSUE TITLE
Getting this to work on Windows

### ISSUE THREAD

**Issue by victoryc** [Jia-Research-Lab/PointGroup#8]
Has anyone managed to get this working on Windows?

- The first issue I encountered while following the installation instructions was when I got the PackagesNotFoundError for the
"conda install -c bioconda google-sparsehash" step. I managed to solve that by searching and using another channel that provides google-sparsehash package. Specifically, I used "conda install -c jithinpr2 google-sparsehash".
- The next issue I encountered was again a PackagesNotFoundError  at the "conda install -c daleydeng gcc-5" step. My work around was again to use another channel for this. I used "conda install -c jithinpr2 libgcc-5". What is available there however is gcc v5.2.0 (and not 5.4). It remains to be seem whether 5.2.0 suffices.
- The next issue I am currently stuck at is at the step "python setup.py bdist_wheel" to compile spconv. I am getting "NotImplementedError" on line 36 of setup.py where it says the script code isn't implemented for Windows. Has anyone managed to fix this?

Thanks.

**Comment by llijiang** [comment]
Hi, you may follow the [spconv](https://github.com/traveller59/spconv) to install spconv on Windows but remember to make  the [changes](https://github.com/llijiang/spconv/commit/740a5b717fc576b222abc169ae6047ff1e95363f) in the spconv/functional.py.

**Comment by victoryc** [comment]
I tried that a bit. Unfortunately, even people who have put in quite a bit of effort to get around the build issues don't seem to have succeeded there, as the comment at https://github.com/traveller59/spconv/issues/161 indicates.

**Comment by victoryc** [comment]
Hi llijiang , though the sparse convolution implementation you used doesn't work on Windows, it seems that the sparse convolution implementation by Facebook (https://github.com/facebookresearch/SparseConvNet) supposedly works on Windows. Do you have any thoughts on how much work it may be to get the rest of your code to work with that implementation of sparse convolution?

**Comment by llijiang** [comment]
Hi,
With SparseConvNet, you may use their unet structure [here](https://github.com/facebookresearch/SparseConvNet/tree/master/examples/3d_segmentation) as backbone and score net. There may be also some minor differences in other places (e.g. sparse tensor initialization).

**Comment by rcffc** [comment]
@victoryc Have you been able to get it to work under Windows?

**Comment by victoryc** [comment]
@rcffc, yes, I was able to get it to work on Windows by using SparseConvNet of Facebook. I had left some comments under one of the issues there outlining the changes I had to make to get it work on Windows.

**Comment by iamyouno** [comment]
@victoryc 
Hi, 
I am also trying to install pointgroup on Windows using SparseConvNet, but since most of the functions of spconv and sparseconvnet are different, and I think I need to change pointgroup.py.
So I tried it, but it didn’t seem to work..
Could you please share or give some advice on this?
