### ISSUE TITLE
LR Scheduler question

### ISSUE THREAD

**Issue by nicolas-chaulet** [Jia-Research-Lab/PointGroup#9]
Just going through the codebase again I realised that the config specify that the step epoch for the learning rate scheduler is set to the final epoch. https://github.com/Jia-Research-Lab/PointGroup/blob/a41c2cd22808861f0d4986b2825875c10bb661e5/config/pointgroup_default_scannet.yaml#L35
This means that at the end of the training the learning rate will be devided by 2, is this correct?
Many thanks

**Comment by llijiang** [comment]
It means that we do not decay the learning rate. It is used in our network-tuning and we found that the lr decay does not affect the performance much in val set.

**Comment by nicolas-chaulet** [comment]
ALright, thanks!
